# SIMPLE DNSMASQ CONFIG FOR BRUTAL ATTACK
interface=wlan0
dhcp-range=192.168.1.100,192.168.1.200,255.255.255.0,12h
dhcp-option=3,192.168.1.1
dhcp-option=6,192.168.1.1
listen-address=192.168.1.1
bind-interfaces
no-resolv
log-queries
log-facility=/var/log/dnsmasq.log